/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

import javax.swing.JOptionPane;

/**
 *
 * @author pedrosaura
 */
public class Ej8_17 extends javax.swing.JFrame {

    /**
     * Creates new form Ej8_17
     */
    public Ej8_17() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAlumno = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        lblNota = new javax.swing.JLabel();
        txfNota = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introducción Notas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        lblCodigo.setDisplayedMnemonic('C');
        lblCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblCodigo.setLabelFor(txfCodigo);
        lblCodigo.setText("Código:");

        txfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfCodigoFocusGained(evt);
            }
        });
        txfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCodigoActionPerformed(evt);
            }
        });

        lblNota.setDisplayedMnemonic('N');
        lblNota.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblNota.setLabelFor(txfNota);
        lblNota.setText("Nota:");

        txfNota.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNota.setText("0");
        txfNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNotaActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAlumnoLayout = new javax.swing.GroupLayout(panAlumno);
        panAlumno.setLayout(panAlumnoLayout);
        panAlumnoLayout.setHorizontalGroup(
            panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlumnoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAlumnoLayout.createSequentialGroup()
                        .addGroup(panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblNota))
                        .addGap(18, 18, 18)
                        .addGroup(panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panAlumnoLayout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(29, 29, 29))))
        );
        panAlumnoLayout.setVerticalGroup(
            panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAlumnoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNota)
                    .addComponent(txfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCodigoActionPerformed

    private void txfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfCodigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCodigoFocusGained

    private void txfNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNotaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        String codigo, notaCad;
        codigo = txfCodigo.getText().trim();
        notaCad = txfNota.getText().trim();
        
        int nota;
        nota = 0;

        if (codigo.length() != 4) 
        {
            JOptionPane.showMessageDialog(this, "Campo obligatorio", "Error en Código", JOptionPane.ERROR_MESSAGE);
            txfCodigo.requestFocus();
            return;
        }

        if (!notaCad.isEmpty()) 
        {
            try 
            {
                nota = Integer.parseInt(notaCad);
                if (nota < 0 || nota > 10) 
                {
                    throw new NumberFormatException();
                }
            } 
            catch (NumberFormatException e) 
            {
            JOptionPane.showMessageDialog(this, "Debe estar entre 0 y 10", "Error en nota", JOptionPane.ERROR_MESSAGE);
            txfNota.requestFocus();
            return;
            }
        }

        Alumno alu = new Alumno(codigo, nota);
        JOptionPane.showMessageDialog(this, "Código: " + alu.getCodigo() + "\nNota: " + alu.getNota(), "Datos a almacenar", JOptionPane.INFORMATION_MESSAGE);                                          

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int dialogoRdo;
        dialogoRdo = JOptionPane.showConfirmDialog (null, "¿Desea salir de la aplicación?","Salir", JOptionPane.YES_NO_OPTION);
        
        if(dialogoRdo == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txfCodigo.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej8_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej8_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej8_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej8_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNota;
    private javax.swing.JPanel panAlumno;
    private javax.swing.JTextField txfCodigo;
    private javax.swing.JTextField txfNota;
    // End of variables declaration//GEN-END:variables
}
